### ISSUE TITLE
add an autogen.sh or instructions on bootstrapping the build

### ISSUE THREAD

**Issue by vbatts** [cyphar/remainroot#1]
i don't mind autotools, but do not like re-learning them every time :-P
Basic things like `autoconf`, `automake`, and `autoreconf` did not get the project `./configure`'able :-\

**Comment by cyphar** [comment]
I just checked and `autreconf -i` made everything `./configure`-able. What does `autogen.sh` usually contain?

**Comment by vbatts** [comment]
if your `./configure` works now, then `autogen.sh` is not required. It job is just to do the needed to make a project configure'able.
I just tried `autoreconf -i` and it worked fine.
